---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "kind/chore"
      - "area/ci"
      - "bots"
    ignore:
      - dependency-name: github.com/aws/aws-sdk-go
        update-types:
          - version-update:semver-patch

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    labels:
      - "kind/chore"
      - "area/ci"
      - "bots"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "kind/chore"
      - "area/ci"
      - "bots"
