---
name: Pull Request
on:
  pull_request:
    branches:
      - main
      - 'v*'
jobs:
  test-and-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/cerbos-cloud-api/bin
          key: generate-${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            generate-${{ runner.os }}-go-

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
          args: '--config=.golangci.yaml'

      - name: Test
        run: make test
